name: Python CI

# Define quais eventos disparam o pipeline
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Faz o checkout (baixa) do código do seu repositório na máquina virtual
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configura a versão do Python
    - name: Set up Python
      uses: actions/actions-setup-python@v5
      with:
        python-version: '3.9.6' # Você pode alterar para a versão que está usando localmente

    # 3. Instala as dependências necessárias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # 4. Executa os testes usando o módulo do Python para evitar problemas de import
    - name: Run tests with pytest
      run: |
        python -m pytest